language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - ./gradlew test jacocoTestReport
  
after_success:
  - bash <(curl -s https://codecov.io/bash)  
