language: android

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26

script:
  - ./gradlew test jacocoTestReport
  
after_success:
  - bash <(curl -s https://codecov.io/bash)  
